image_width: 1920
image_height: 1080
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [1102.46878,    0.     ,  904.49107,
            0.     , 1116.20224,  420.3918 ,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.378934, 0.110940, 0.009671, 0.008795, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [784.46564,   0.     , 946.99405,   0.     ,
           0.     , 993.51782, 402.84639,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
