image_width: 1920
image_height: 1080
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [1138.037  ,    0.     ,  966.63586,
            0.     , 1143.69047,  473.50836,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.416280, 0.141958, -0.000204, -0.000645, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [ 822.08325,    0.     ,  962.64264,    0.     ,
            0.     , 1014.42474,  455.45788,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
