image_width: 1920
image_height: 1080
camera_name: narrow_stereo_L21
camera_matrix:
  rows: 3
  cols: 3
  data: [1123.06489,    0.     ,  925.5334 ,
            0.     , 1120.25401,  486.66973,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.369887, 0.107857, -0.005248, 0.006479, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [ 780.01764,    0.     ,  959.76167,    0.     ,
            0.     , 1002.44971,  467.16934,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
